version: 2
updates:
  # Enable version updates for Bun
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Mihn1234"
    assignees:
      - "Mihn1234"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      production-dependencies:
        patterns:
          - "react*"
          - "next*"
          - "@types/*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
          - "biome"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Mihn1234"
    assignees:
      - "Mihn1234"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
